[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure static assets are copied
[build.processing]
  skip_processing = false

[build.processing.images]
  compress = true

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 