-- Seed data for Spindrift products
INSERT INTO public.products (brand_id, name, description, flavor, carbonation_level, container_type, container_size, nutrition_info) VALUES
    ('07ec3e96-7564-4fda-be69-eec6d50126b6', 'Cosmopolitan', 'A sophisticated blend featuring real cranberry, orange, and lime juices creating a sparkling mocktail inspired by the classic cocktail.', ARRAY['cranberry', 'orange', 'lime'], 8, 'can', '12 fl oz', '{"ingredients": "Carbonated water, cranberry juice, orange juice, lime juice", "calories": 10, "total_fat": 0, "saturated_fat": 0, "carbohydrates": 3, "sugars": 2, "proteins": 0, "serving_size": "12 FL OZ (355ML)"}'),
    
    ('07ec3e96-7564-4fda-be69-eec6d50126b6', 'Fuji Apple', 'Made with real Fuji apple juice, offering a crisp and naturally sweet taste that captures the essence of fresh-picked apples.', ARRAY['fuji apple'], 8, 'can', '12 fl oz', '{"ingredients": "Carbonated water, Fuji apple juice, citric acid", "calories": 20, "total_fat": 0, "saturated_fat": 0, "carbohydrates": 5, "sugars": 4, "proteins": 0, "serving_size": "12 FL OZ (355ML)"}'),
    
    ('07ec3e96-7564-4fda-be69-eec6d50126b6', 'Grapeade', 'A refreshing blend of real concord grape and lemon juices, delivering the nostalgic taste of grape soda without artificial ingredients.', ARRAY['grape'], 8, 'can', '12 fl oz', '{"ingredients": "Carbonated water, concord grape juice, lemon juice", "calories": 14, "total_fat": 0, "saturated_fat": 0, "carbohydrates": 3, "sugars": 2, "proteins": 0, "serving_size": "12 FL OZ (355ML)"}'),
    
    ('07ec3e96-7564-4fda-be69-eec6d50126b6', 'Island Punch', 'A tropical medley combining real passion fruit, orange, and guava juices for an island-inspired refreshment.', ARRAY['passion fruit', 'orange', 'guava'], 8, 'can', '12 fl oz', '{"ingredients": "Carbonated water, guava puree, passion fruit juice, orange juice, citric acid", "calories": 13, "total_fat": 0, "saturated_fat": 0, "carbohydrates": 3, "sugars": 2, "proteins": 0, "serving_size": "12 FL OZ (355ML)"}'),
    
    ('07ec3e96-7564-4fda-be69-eec6d50126b6', 'Nojito', 'A non-alcoholic take on the mojito, featuring real lime juice and fresh mint for a crisp, clean taste.', ARRAY['lime', 'mint'], 8, 'can', '12 fl oz', '{"ingredients": "Carbonated water, lime juice, mint", "calories": 4, "total_fat": 0, "saturated_fat": 0, "carbohydrates": 1, "sugars": 0, "proteins": 0, "serving_size": "12 FL OZ (355ML)"}'),
    
    ('07ec3e96-7564-4fda-be69-eec6d50126b6', 'Mango Black Tea', 'A unique fusion of real mango puree and brewed black tea, creating a refreshing twist on traditional iced tea.', ARRAY['tea', 'mango'], 8, 'can', '12 fl oz', '{"ingredients": "Carbonated water, mango puree, lemon juice, brewed black tea", "calories": 11, "total_fat": 0, "saturated_fat": 0, "carbohydrates": 3, "sugars": 2, "proteins": 0, "serving_size": "12 FL OZ (355ML)"}'),
    
    ('07ec3e96-7564-4fda-be69-eec6d50126b6', 'Peach Strawberry', 'A perfect pairing of real peach and strawberry purees, delivering a naturally sweet and fruity combination.', ARRAY['peach', 'strawberry'], 8, 'can', '12 fl oz', '{"ingredients": "Carbonated water, peach puree, strawberry puree, citric acid", "calories": 13, "total_fat": 0, "saturated_fat": 0, "carbohydrates": 3, "sugars": 2, "proteins": 0, "serving_size": "12 FL OZ (355ML)"}'),
    
    ('07ec3e96-7564-4fda-be69-eec6d50126b6', 'Raspberry Lime', 'A vibrant combination of real raspberry puree and lime juice creating a perfectly balanced berry-citrus blend.', ARRAY['raspberry', 'lime'], 8, 'can', '12 fl oz', '{"ingredients": "Carbonated water, raspberry puree, lime juice", "calories": 5, "total_fat": 0, "saturated_fat": 0, "carbohydrates": 1, "sugars": 1, "proteins": 0, "serving_size": "12 FL OZ (355ML)"}'),
    
    ('07ec3e96-7564-4fda-be69-eec6d50126b6', 'Grapefruit', 'Made with real grapefruit juice and a hint of orange and lemon, delivering a tart and refreshing citrus experience.', ARRAY['grapefruit'], 8, 'can', '12 fl oz', '{"ingredients": "Carbonated water, grapefruit juice, orange juice, lemon juice, hibiscus", "calories": 17, "total_fat": 0, "saturated_fat": 0, "carbohydrates": 4, "sugars": 3, "proteins": 0, "serving_size": "12 FL OZ (355ML)"}'),
    
    ('07ec3e96-7564-4fda-be69-eec6d50126b6', 'Blood Orange Tangerine', 'A citrus lovers delight combining real blood orange and tangerine juices for a complex and refreshing flavor.', ARRAY['blood orange', 'tangerine'], 8, 'can', '12 fl oz', '{"ingredients": "Carbonated water, blood orange juice, tangerine juice, citric acid", "calories": 12, "total_fat": 0, "saturated_fat": 0, "carbohydrates": 3, "sugars": 2, "proteins": 0, "serving_size": "12 FL OZ (355ML)"}'),
    
    ('07ec3e96-7564-4fda-be69-eec6d50126b6', 'Half Tea & Half Lemon', 'A sparkling twist on the classic Arnold Palmer, featuring brewed black tea and real lemon juice.', ARRAY['tea', 'lemon'], 8, 'can', '12 fl oz', '{"ingredients": "Carbonated water, lemon juice, brewed black tea", "calories": 5, "total_fat": 0, "saturated_fat": 0, "carbohydrates": 1, "sugars": 0, "proteins": 0, "serving_size": "12 FL OZ (355ML)"}'),
    
    ('07ec3e96-7564-4fda-be69-eec6d50126b6', 'Mango Orange', 'A tropical blend of real mango puree and orange juice creating a sunny, fruit-forward refreshment.', ARRAY['mango', 'orange'], 8, 'can', '12 fl oz', '{"ingredients": "Carbonated water, mango puree, orange juice, citric acid", "calories": 12, "total_fat": 0, "saturated_fat": 0, "carbohydrates": 3, "sugars": 3, "proteins": 0, "serving_size": "12 FL OZ (355ML)"}'),
    
    ('07ec3e96-7564-4fda-be69-eec6d50126b6', 'Lime', 'Simple and refreshing with real lime juice, offering a clean and crisp citrus taste.', ARRAY['lime'], 8, 'can', '12 fl oz', '{"ingredients": "Carbonated water, lime juice", "calories": 4, "total_fat": 0, "saturated_fat": 0, "carbohydrates": 1, "sugars": 0, "proteins": 0, "serving_size": "12 FL OZ (355ML)"}'),
    
    ('07ec3e96-7564-4fda-be69-eec6d50126b6', 'Lemon', 'A bright and zesty sparkling water made with real lemon juice for authentic citrus flavor.', ARRAY['lemon'], 8, 'can', '12 fl oz', '{"ingredients": "Carbonated water, lemon juice", "calories": 3, "total_fat": 0, "saturated_fat": 0, "carbohydrates": 1, "sugars": 0, "proteins": 0, "serving_size": "12 FL OZ (355ML)"}'),
    
    ('07ec3e96-7564-4fda-be69-eec6d50126b6', 'Pineapple', 'Made with real pineapple juice for a tropical escape in every sip.', ARRAY['pineapple'], 8, 'can', '12 fl oz', '{"ingredients": "Carbonated water, pineapple juice, citric acid", "calories": 15, "total_fat": 0, "saturated_fat": 0, "carbohydrates": 4, "sugars": 3, "proteins": 0, "serving_size": "12 FL OZ (355ML)"}'),
    
    ('07ec3e96-7564-4fda-be69-eec6d50126b6', 'Pink Lemonade', 'A colorful twist on classic lemonade with real cherry, lime, and lemon juices, naturally colored with hibiscus.', ARRAY['pink lemon'], 8, 'can', '12 fl oz', '{"ingredients": "Carbonated water, cherry juice, lime juice, lemon juice, hibiscus", "calories": 10, "total_fat": 0, "saturated_fat": 0, "carbohydrates": 2, "sugars": 1, "proteins": 0, "serving_size": "12 FL OZ (355ML)"}'),
    
    ('07ec3e96-7564-4fda-be69-eec6d50126b6', 'Lemon Limeade', 'A perfect balance of real lemon and lime juices for a classic citrus combination.', ARRAY['lemon', 'lime'], 8, 'can', '12 fl oz', '{"ingredients": "Carbonated water, lime juice, lemon juice", "calories": 4, "total_fat": 0, "saturated_fat": 0, "carbohydrates": 1, "sugars": 0, "proteins": 0, "serving_size": "12 FL OZ (355ML)"}'),
    
    ('07ec3e96-7564-4fda-be69-eec6d50126b6', 'Strawberry Lemonade', 'A fruity twist on lemonade combining real strawberry puree with lemon and lime juices.', ARRAY['strawberry', 'lemon'], 8, 'can', '12 fl oz', '{"ingredients": "Carbonated water, strawberry puree, lime juice, lemon juice", "calories": 7, "total_fat": 0, "saturated_fat": 0, "carbohydrates": 2, "sugars": 1, "proteins": 0, "serving_size": "12 FL OZ (355ML)"}'); 